# Generated by Django 5.1.7 on 2025-03-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Data Analysis', 'Data Analysis'), ('Machine Learning', 'Machine Learning'), ('Visualization', 'Visualization'), ('Django', 'Django')], max_length=50),
        ),
    ]
