# Generated by Django 5.1.7 on 2025-03-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='source',
            field=models.CharField(choices=[('Google', 'Google'), ('Infosys Springboard', 'Infosys Springboard'), ('Microsoft Azure', 'Microsoft Azure'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
