# Generated by Django 5.1.7 on 2025-03-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
