# Generated by Django 5.1.7 on 2025-03-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_resume_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='source',
            field=models.CharField(choices=[('Google', 'Google'), ('Infosys Springboard', 'Infosys Springboard'), ('Microsoft Azure', 'Microsoft Azure'), ('Other', 'Other'), ('NPTEL', 'NPTEL')], default='Other', max_length=50),
        ),
    ]
