# Generated by Django 5.1.7 on 2025-03-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_certification_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('technologies', models.CharField(max_length=200)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='internship_certificates/')),
            ],
        ),
        migrations.AlterField(
            model_name='certification',
            name='source',
            field=models.CharField(choices=[('Google', 'Google'), ('Infosys Springboard', 'Infosys Springboard'), ('Microsoft Azure', 'Microsoft Azure'), ('NPTEL', 'NPTEL'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
